apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-info
  namespace: argocd
  labels:
    app.kubernetes.io/name: cluster-info
    app.kubernetes.io/part-of: everyday-devops-demos
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_ORG/cluster-info.git
    targetRevision: main
    path: k8s/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: cluster-info
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
